import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
const goldmanBold = localFont({
  src: "../fonts/fonts/fonnts.com-Goldman_Bold.ttf",
  variable: "--font-goldman-bold",
  weight: "700",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ fontFamily: goldmanBold.style.fontFamily }}>
      <body
        className={`${goldmanBold.variable} antialiased`}
        style={{ fontFamily: goldmanBold.style.fontFamily }}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}